app.version: '@project.version@'

spring:
  application:
    name: mongo-shop
  data:
    mongodb:
      uri: mongodb://localhost:27017/shop
      database: shop

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core: DEBUG

# Swagger configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html